# Generated by Django 5.1.1 on 2024-09-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_rename_student_id_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="mother_occupation",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
