# Generated by Django 5.1.1 on 2024-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_auth", "0003_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="AbP2GmVLBBFvZzHSR3HBfojqVGBnCg9F",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
