# Generated by Django 5.1.1 on 2024-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_auth", "0004_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="kNl6MPiOJ8wj1nd6odXT0DqBY7h43UWW",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
